# Generated by Django 5.0.3 on 2024-04-03 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_alter_answer_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название заведения')),
                ('city_country', models.CharField(max_length=255, verbose_name='Страна и город')),
                ('address', models.CharField(max_length=200, unique=True, verbose_name='Адрес')),
                ('business_type', models.CharField(max_length=50, verbose_name='Тип бизнеса')),
                ('direction', models.CharField(max_length=50, verbose_name='Направление')),
                ('service_type', models.CharField(max_length=50, verbose_name='Тип сервисов')),
            ],
            options={
                'verbose_name': 'Заведение',
                'verbose_name_plural': 'Заведения',
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.AddField(
            model_name='answer',
            name='clarification',
            field=models.CharField(max_length=255, null=True, verbose_name='Уточнение'),
        ),
        migrations.AlterField(
            model_name='question',
            name='comment',
            field=models.TextField(null=True, verbose_name='Дополнительный комментарий'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.ManyToManyField(to='questionnaire.answer', verbose_name='Ответы')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
    ]
