# Generated by Django 5.0.3 on 2024-04-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_institution_remove_question_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='clarification',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Уточнение'),
        ),
        migrations.AlterField(
            model_name='question',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительный комментарий'),
        ),
    ]
